### ISSUE TITLE
Oversweep bug

### ISSUE THREAD

**Issue by MaryCBaylis** [secade/ruby-sweeper#7]
I figured I'd use github for once, yay!  Game.rb's call to oversweep would cause the correct coordinate to be swept, but the inverse of that coordinate to be overswept.  To fix it, I switched the x and y ;coordinates in Game.rb's call.  THIS SHOULD NOT BE WORKING.  But for some reason it does.  Please help me figure out why. ;_;

Screen shots from before bug fix:
![screen shot 2015-01-31 at 1 24 30 am](https://cloud.githubusercontent.com/assets/10081989/5987169/fe8260b2-a8eb-11e4-98b3-e74f69f96175.png)
![screen shot 2015-01-31 at 1 16 42 am](https://cloud.githubusercontent.com/assets/10081989/5987170/0392d3de-a8ec-11e4-9787-d910c03d9cb2.png)

See the code in Game.rb and Board.rb for specific comments.

**Comment by secade** [comment]
This was my mistake- found it and fixed it! See board.rb:

![image](https://cloud.githubusercontent.com/assets/8475694/5990461/ad6f583e-a980-11e4-8ad4-000db378b827.png)

I had previously been using very ugly code to select the appropriate cell objects and recently cleaned it up when I remembered a better way to select the objects (cell or mine) held in the 2d @board array. I implemented the cleaner code but forgot one big issue- the order of x and y, or i and j.

In lines 35-40, you'll see two different ways of handling x/y or i/j- first is using standard 2d array calls [j][i] and then the second is as method parameters (i, j). In the 2d array calls, the Y coord MUST come first, but in the method params, X must come first. When I switched everything over to the [][] syntax, I forgot about this and this broke oversweep. I've fixed it and tested for ya- great catch and perfect report/documentation!
